---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgAYJP32wPZ6CTaoLDun2JYawn9BXkqeo5ezkR0g1S8dI7ikHpd2eWv1M8cqxhZZlYvbLAtVl+It6no+IbvXj+aPfcQiJz0zi/2RA0D6BmP6KwRaj4QE5ffS8P8MpnPDerM7YUxps1/CH3u5IvdjiR7jlvHCUXqCVlU0NSFiIx0XUJpq5b9SMA2q25qHYERKi6+19j8tE/MyTZK0VSVwmTcVV2DhjoNminyn9iIoGPNSOV2UU8jdbSu8lua5ossXCP+SAwbWqR8SiuP91m4dU/akSltVDRD2bPnzv+sdSpuCkTgBT/Fj14AfyXSkg66FrhHf6tTv9t9ePpxkakH8FPHk3usBr9ENfd3Ml2bvQ+xZxe6aBr67FEq5zypP93yoox3h7jc6FQVfnjG3yjepwmaAh40tVmRZOFTgUUavMeYU0LRoUfJurDDhbHYRAbGpPDyyyyO2Byv+9FoYetsdhsLKCg7VGmeCjMZ2vY/ksBfSflVGgKjrzEzF0IsgGTCdZGWNfCIGLEAm6XLI8wLPGZetLbrTiy8DuedU1GuQBj6sW5Wvpd27yXTsDDAa8TdREOFPAyfrg1hwXY/bVThPtk5TVTtcL/fHdodoeooseX0lVyUdim4H+1qZ23WHdWn+fa4aoSYJWWQ1DSIKccROpLDqD7mKJSLlRoTopL7KhK/vnUEU0iuaMvlLuR8RhCPMXdj74X97uxR/XqGvXw==
    STRIPE_API_KEY: AgAlf63QVauLww+ZWSJxXe7rTP5FuXgfmMC9yoXQrkHkx8t6+tRTR1gjHXKoquoLaRrPfEz1w5ryE9uD9mKnnYGt68FecwnC0LN6KUDDu2q/S8pPAJpCyAkEqayuhrRevhJeraX4jjVQrXGWAZLB9qKOasKI44/BfQWrCHyVKf+WZerRVtremBTKRRbj2S6E0HuxVigdB9hFJoOp9B7FHqOSmzaE7T4DhyRCbNS94MNPB8gZTcxV8BTD6Ba+YTjs0RmLdQhdqYiYwl5wN5tlMmq4LLXYc8kZI2g0i5pAZOT54PimTo7JjlOHaA/+oZqjkx9EPLTRUibJjq1sMmUeD3LrGqcuEJHfDamv92rUfGTTaxldr6Cqpxv3wbt0AUO8Fp68mtlUiCIRhrGmugHp7zOK8yeIKTYmnDUuPdpORTTt5o2ZUCMwJmnsSUlpN8zDEOd11SljMsiK/p+uZX5q+N8Fy4vk6a9XQh6/mOhLiK+0xSSsm0895Z1lupdoWOuV3DcjS/4YTLsc0yVY9XiWU7UALzMc6bkLyHbNTmqI3VY33t1475zof3XRoMn8cc/rUHdcDhaVSL0oBCKbLnUbxLtli1tXVKiwhnVw6UiqYxRqjD7hz0ecADHNZOuoNicFai7xyxBT84ZqeXPIlCQruvGACVkdXRFLzYWtfL65CkCB1ChR4zt7EwIgZnLun/P+qaiEByIPEyCjr/D0oJL9I5L5Vh9ywO9YVbweCvyi5Q==
  template:
    metadata:
      name: ledger-api-secrets
      namespace: payments
    type: Opaque
